package com.kagi.summarizer

// Available Kagi Summarizer languages
val SUMMARY_LANGUAGES = linkedMapOf(
    "Default" to "",
    "Bulgarian" to "BG",
    "Chinese (simplified)" to "ZH",
    "Chinese (traditional)" to "ZH-HANT",
    "Czech" to "CS",
    "Danish" to "DA",
    "Dutch" to "NL",
    "English" to "EN",
    "Estonian" to "ET",
    "Finnish" to "FI",
    "French" to "FR",
    "German" to "DE",
    "Greek" to "EL",
    "Hungarian" to "HU",
    "Indonesian" to "ID",
    "Italian" to "IT",
    "Japanese" to "JA",
    "Korean" to "KO",
    "Latvian" to "LV",
    "Lithuanian" to "LT",
    "Norwegian" to "NB",
    "Polish" to "PL",
    "Portuguese" to "PT",
    "Romanian" to "RO",
    "Russian" to "RU",
    "Slovak" to "SK",
    "Slovenian" to "SL",
    "Spanish" to "ES",
    "Swedish" to "SV",
    "Turkish" to "TR",
    "Ukrainian" to "UK",

    )